language: python
python:
  - "3.6"

addons:
  rethinkdb: "2.3"

branches:
  only:
    - "master"

sudo: required

services:
  - docker

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev --three
script:
  - pipenv run lint
  - pipenv run python gunicorn_config.py
  - pipenv run test
  - pipenv run coveralls
after_success:
  - bash scripts/deploy.sh

cache: pip

notifications:
  email: false
