name: Build & Deploy Static Preview

on:
  pull_request:

jobs:
  build:
    name: Build Static Preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install netlify-cli -g

     # Create a commit SHA-based tag for the container repositories
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the container, including an inline cache manifest to
      # allow us to use the registry as a cache source.
      - name: Build & Push Base Image
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: ./Dockerfile
          push: false
          cache-from: type=registry,ref=ghcr.io/hassanabouelela/static-site:latest
          cache-to: type=inline
          tags: |
            ghcr.io/hassanabouelela/static-site:latest
            ghcr.io/hassanabouelela/static-site:${{ steps.sha_tag.outputs.tag }}
          build-args: |
            git_sha=${{ github.sha }}

      - name: Build Local Docker Image
        run: |
          docker build \
          --build-arg git_sha=${{ github.sha }} \
          --cache-from ghcr.io/hassanabouelela/static-site:latest \
          -t static-site:${{ steps.sha_tag.outputs.tag }} \
          .

      - name: Extract Build From Docker Image
        run: |
          docker run --name site static-site:${{ steps.sha_tag.outputs.tag }} \
          && docker cp site:/app/build build/

      - run: netlify login && netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
      - run: netlify deploy --dir=build
